### ISSUE TITLE
European Union Map: Northern Ireland is grouped with Ireland, not GB

### ISSUE THREAD

**Issue by fscholz** [neveldo/mapael-maps#12]
Northern Ireland is grouped with Ireland, not GB

While this might be correct from a naming perspective, it is wrong with regard to the European Union since not GB is part of the EU, but the United Kingdom (that includes Northern Ireland) is.

I'll try to fix it at some point; however, I am new to GitHub and have yet to figure out how to contribute to a project.

**Comment by neveldo** [comment]
Hello,

Thank you for reporting this issue regarding Northern Ireland. I will try to fix it as soon as possible, but feel free to contribute if you can. You just have to fork the mapael-maps project, commit your fix and make a pull-request to the orginal project. All the steps are explained here : https://help.github.com/articles/creating-a-pull-request/ .

In order to edit the map, you can follow this tutorial : http://www.vincentbroute.fr/mapael/create-map.php . An online tool allows to to convert a mapael maps to SVG format.

**Comment by 10YAR** [comment]
Corrected version is available in this pull request : https://github.com/neveldo/mapael-maps/pull/85
I removed Northern Ireland from the "Ireland" shape and created a new shape for Northern Ireland (named "GB-NIR")

**Comment by neveldo** [comment]
Thanks for your fix @10YAR :)
