### ISSUE TITLE
Romania map

### ISSUE THREAD

**Issue by razvan925** [neveldo/mapael-maps#17]
Hello,

I'm trying to use SVG to Mapael to get the map of Romania. 
It works but in order to see the country map i have to scroll down. 
The svg i'm using is this: 
                https://commons.wikimedia.org/wiki/File:Romania_location_map.svg

Can you please help?

Thank you

**Comment by Indigo744** [comment]
The SVG file seems fine. It depends on what you did when converting to mapael.
Did you follow the tutorial here http://www.vincentbroute.fr/mapael/create-map.php ?
Can you provide a JSFiddle example?

**Comment by razvan925** [comment]
I just saved the SVG file and used SVG to Mapael, without any other changes.

**Comment by razvan925** [comment]
Jsfiddle here: http://jsfiddle.net/tn5AF/649/

**Comment by Indigo744** [comment]
If you had followed the tutorial, and open the SVG file in Inkscape as described, you would have seen this:
![SVG Map in Inkscape](http://postimg.org/image/uv5n5ue03/)

As you can see, the document boundaries (represented by a rectangle on the top left) are **not** around the paths. Hence why when converting, you get this huge space.

In order to circumvent the problem, simply follow the tutorial. Open the file in Inkscape and fit the page to content:
> The areas in the new document may not fit with the document dimensions. In this case, go to File > Document Properties > Resize page to content, and click on the “Resize page to drawing or selection”.

**Comment by razvan925** [comment]
It worked!

Thank you

**Comment by Indigo744** [comment]
As a side note, the map in http://www.amcharts.com/svg-maps/?map=romania use the Mercator projection and not the equirectangular projection.
